### ISSUE TITLE
Memory does not decrease with a large list.

### ISSUE THREAD

**Issue by vantrung8794** [letsar/flutter_staggered_grid_view#180]
Memory does not decrease with a large list. I tried SliverStaggeredGrid.builder and SliverStaggeredGrid.countBuilder with a large number of tiles. When I scroll, the old item in the grid which disappeared still alive and took lots of my memory. The problem is when my list has many items. App will crash because the memory is not enough.
=> I tried to change to Gridview.builder. The problem is solved. Gridview.builder release old item which disappeared and rebuild when items are showed on screen.

**Comment by vantrung8794** [comment]
any one has a solution for this situation?

**Comment by clragon** [comment]
The reason for this is that all children of the grid are cached indefinitely.

Currently there is no way of disabling this behaviour.
However, I have opened PR #188 that allows this.

**Comment by bladeofgod** [comment]
me too. and study on it.

**Comment by ap1781994** [comment]
go with waterfall_flow: ^3.0.1 it working good

**Comment by babaosoftware** [comment]
I experienced the same problem, which is a deal breaker for me, as I have 1000+ items in the grid. Especially when rotating the phone, it's horrendous to redraw, and I can see it going through all items up to the scroll point. 
I initially thought there was something wrong with my implementation, but now I see a lot of people with the same problem.
I am currently using GridView.builder, which is fast, no problems, except that I'm stuck with same size tiles.

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by ap1781994** [comment]
Use https://pub.dev/packages/waterfall_flow it working good no issues of
size and large data

**Comment by letsar** [comment]
This comment does not help. The package has beed rewritten and the performance issues has been resolved for what I can tell.
@vantrung8794 I suggest you to try the latest version available:  https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by ap1781994** [comment]
Ok, I'll check it out.

**Comment by LoremIpsum1512** [comment]
confirmed


> This comment does not help. The package has been rewritten and the performance issues has been resolved for what I can tell. @vantrung8794 I suggest you to try the latest version available: https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by yaozy003** [comment]
Still have this proble么nowadays with v0.6.1， I ll go with waterfall flow

**Comment by letsar** [comment]
Have you some code I could just copy/paste and run to see where the issue comes from?

**Comment by letsar** [comment]
Closing since no response since a while.
