### ISSUE TITLE
Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'

### ISSUE THREAD

**Issue by KagurazakaHanabi** [letsar/flutter_staggered_grid_view#49]
## flutter doctor
```
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v1.5.9-pre.188, on Microsoft Windows [Version 10.0.18356.16], locale zh-CN)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 3.4)
[√] VS Code (version 1.33.1)
[√] Connected device (2 available)

• No issues found!
```

## Logs
```
E/flutter ( 2748): [ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'
E/flutter ( 2748): #0      RenderSliverVariableSizeBoxAdaptor.hitTestChildren (package:flutter_staggered_grid_view/src/rendering/sliver_variable_size_box_adaptor.dart:380:27)
E/flutter ( 2748): #1      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1273:11)
E/flutter ( 2748): #2      SliverHitTestResult.addWithAxisOffset (package:flutter/src/rendering/sliver.dart:850:19)
E/flutter ( 2748): #3      RenderSliverPadding.hitTestChildren (package:flutter/src/rendering/sliver_padding.dart:266:14)
E/flutter ( 2748): #4      RenderSliver.hitTest (package:flutter/src/rendering/sliver.dart:1273:11)
E/flutter ( 2748): #5      RenderViewportBase.hitTestChildren.<anonymous closure> (package:flutter/src/rendering/viewport.dart:585:24)
E/flutter ( 2748): #6      BoxHitTestResult.addWithRawTransform (package:flutter/src/rendering/box.dart:791:19)
E/flutter ( 2748): #7      BoxHitTestResult.addWithPaintTransform (package:flutter/src/rendering/box.dart:722:12)
E/flutter ( 2748): #8      RenderViewportBase.hitTestChildren (package:flutter/src/rendering/viewport.dart:581:33)
E/flutter ( 2748): #9      RenderBox.hitTest (package:flutter/src/rendering/box.dart:2100:11)
E/flutter ( 2748): #10     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 2748): #11     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2100:11)
E/flutter ( 2748): #12     RenderIgnorePointer.hitTest (package:flutter/src/rendering/proxy_box.dart:2963:37)
E/flutter ( 2748): #13     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 2748): #14     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2100:11)
E/flutter ( 2748): #15     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 2748): #16     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:161:19)
E/flutter ( 2748): #17     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 2748): #18     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2100:11)
E/flutter ( 2748): #19     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 2748): #20     RenderProxyBoxWithHitTestBehavior.hitTest (package:flutter/src/rendering/proxy_box.dart:161:19)
E/flutter ( 2748): #21     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 2748): #22     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2100:11)
E/flutter ( 2748): #23     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 2748): #24     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2100:11)
E/flutter ( 2748): #25     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 2748): #26     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:508:18)
E/flutter ( 2748): #27     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2100:11)
E/flutter ( 2748): #28     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 2748): #29     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2100:11)
E/flutter ( 2748): #30     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 2748): #31     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2100:11)
E/flutter ( 2748): #32     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (package:flutter/src/rendering/proxy_box.dart:114:19)
E/flutter ( 2748): #33     RenderCustomPaint.hitTestChildren (package:flutter/src/rendering/custom_paint.dart:508:18)
E/flutter ( 2748): #34     RenderBox.hitTest (package:flutter/src/rendering/box.dart:2100:11)
E/flutter ( 2748): #35     _RenderProxyBox&RenderBox&RenderObjectWithChildMixin&RenderProxyBoxMixin.hitTestChildren (packa
```

**Comment by dereklakin** [comment]
Same here using StaggeredGridView inside a NestedScrollView when trying to scroll.

**Comment by Theunodb** [comment]
Also having this problem.

**Comment by jarekb123** [comment]
Also having this issue.

**Comment by dereklakin** [comment]
It's something to do with the `hitTestChildren` method in `SliverVariableSizeBoxAdapter`. If I revert it to just call `super.hitTestChildren` then scrolling works, but `onTap` on my child items never fires, so there's more to it than that :)

**Comment by dereklakin** [comment]
I've fixed it for my scenario, though I'm not sure if it will work for everyone. In `sliver_variable_size_box_adaptor.dart` change `hitTestChildren` method to:

```  @override
  bool hitTestChildren(HitTestResult result,
      {@required double mainAxisPosition, @required double crossAxisPosition}) {
    for (var child in children) {
      if (hitTestBoxChild(BoxHitTestResult.wrap(result), child,
          mainAxisPosition: mainAxisPosition,
          crossAxisPosition: crossAxisPosition)) return true;
    }
    return false;
  }
```

The important bit is the change to call `BoxHitTestResult.wrap(result)` in the call to `hitTestBoxChild` instead of just passing `result`.

**Comment by korbacsk** [comment]
Same problem.

**Comment by jitenders859** [comment]
same problem

**Comment by vishaakm** [comment]
> I've fixed it for my scenario, though I'm not sure if it will work for everyone. In `sliver_variable_size_box_adaptor.dart` change `hitTestChildren` method to:
> 
> ```
>   bool hitTestChildren(HitTestResult result,
>       {@required double mainAxisPosition, @required double crossAxisPosition}) {
>     for (var child in children) {
>       if (hitTestBoxChild(BoxHitTestResult.wrap(result), child,
>           mainAxisPosition: mainAxisPosition,
>           crossAxisPosition: crossAxisPosition)) return true;
>     }
>     return false;
>   }
> ```
> 
> The important bit is the change to call `BoxHitTestResult.wrap(result)` in the call to `hitTestBoxChild` instead of just passing `result`.

This Fixed the problem for me..

**Comment by cmcgill1988** [comment]
Any news if the PR fixing this is going to get merged in? I'm keen to use this package but until this is fixed I will have to stick with my own implementation which isn't as clean or responsive as this package.

**Comment by letsar** [comment]
Thanks, published in v0.3.0

**Comment by Wood-Water-Peng** [comment]
It's really helpful,I have fixed this problem with overriding the hitTestChildren method。
Thank you!
ps: StaggerGridView inside NestedScrollView

**Comment by mickykebe** [comment]
This solution no longer works since flutter version 1.7.

**Comment by rajesh-kc** [comment]
Upgraded flutter to 1.7 v, Now flutter_staggered_grid_view package is throwing this error "Unhandled Exception: type 'SliverHitTestResult' is not a subtype of type 'BoxHitTestResult'"

Upgraded package to 0.3.0 from 0.2.7, The error remains the same. 

Requesting the author to provide a solution.

**Comment by miguelangarano** [comment]
@dereklakin 's solution works like a charm for me in Flutter 1.7.8+hotfix.3 and last updated Staggered package

**Comment by udit-wynk** [comment]
facing the same issue with Flutter 1.7.8+hotfix.3 and flutter_staggered_grid_view 0.3.0.
Please provide with a fix..

**Comment by sinuraya** [comment]
here is work for me:
1. uprgade flutter_staggered_grid_view to 0.3.0
2. if the problem still persist, delete ~/.pub-cache/hosted/pub.dartlang.org folder
3. run $ flutter pub get 
4. your flutter_staggered_grid_view should work by now

**Comment by xhidnoda** [comment]
After upgrade to 0.3.0 on Flutter 1.7.8.  Running `flutter clean` works for me.

**Comment by nixoncode** [comment]
> After upgrade to 0.3.0 on Flutter 1.7.8. Running `flutter clean` works for me.

This worked for me

**Comment by sunderls** [comment]
above works!

**Comment by gateshibill** [comment]
update flutter_staggered_grid_view: ^0.3.0,it is ok!

**Comment by devrav** [comment]
> update flutter_staggered_grid_view: ^0.3.0,it is ok!

its is working, nice thankyou !

**Comment by dongzhixuanyuan** [comment]
After upgrade to 0.3.0. Running flutter clean works for me. must run flutter clean

**Comment by w4t3r-45** [comment]
> here is work for me:
> 
> 1. uprgade flutter_staggered_grid_view to 0.3.0
> 2. if the problem still persist, delete ~/.pub-cache/hosted/pub.dartlang.org folder
> 3. run $ flutter pub get
> 4. your flutter_staggered_grid_view should work by now

thaaaaaaaaaaaaaank you so much maaan my head burned trying to fix it and now all is working i just updated it to 0.3.0 thaaaaaaaaaaank you maaaaan

**Comment by tibfox** [comment]
> 
> 
> here is work for me:
> 
>     1. uprgade flutter_staggered_grid_view to 0.3.0
> 
>     2. if the problem still persist, delete ~/.pub-cache/hosted/pub.dartlang.org folder
> 
>     3. run $ flutter pub get
> 
>     4. your flutter_staggered_grid_view should work by now

thank you!

**Comment by GirijeshGupta** [comment]
Ya, it's work for me after upgrade 0.3.0
